name: demo
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test-code:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - name: checkout code
        uses: actions/checkout@v3
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run py test
        id: run-py-test
        run: pytest --cov-report html:htmlcov --cov-report term --cov=project tests
      - name: upload test reports
        if: ${{ failure() && steps.run-py-test.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.os }}-${{ matrix.version }}
          path: htmlcov/
  
  deploy:
    runs-on: ubuntu-22.04
    needs: test-code
    if: ${{ success() }} 
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: deploy code
        run: echo "deploy........."
